# VKGroups
#
# Copyright © 2010-2018 HeaTTheatR
#
# Для предложений и вопросов:
# <kivydevelopment@gmail.com>
# 
# Данный файл распространяется по условиям той же лицензии,
# что и фреймворк Kivy.

# Бокс для аттачей в постах и комментариях.

#:import AttachPhoto libs.uix.baseclass.attachphoto.AttachPhoto


<AttachPhoto>:
    _app: app
    size_hint_y: None
    spacing: dp(5)
    padding: dp(5)
    height: root.height
    attach_list: []
    on_attach_list: root.add_attach(root.attach_list)

