# VKGroups
#
# Copyright © 2010-2018 HeaTTheatR
#
# Для предложений и вопросов:
# <kivydevelopment@gmail.com>
# 
# Данный файл распространяется по условиям той же лицензии,
# что и фреймворк Kivy.

# Бокс для аттачей в форме для ввода текста.


<BoxAttachFile>:
    id: box_attach
    orientation: 'vertical'
    size_hint_y: None
    height: self.minimum_height

    canvas:
        Color:
            rgba: 0, 0, 0, 0
        Rectangle:
            pos: self.pos
            size: self.size